music/urls.py
from django.conf.urls import url
from . import views # import views from music directory

app_name = 'music'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name = 'index'), # index for each individual app, means nothing after music/ in url
    # /music/<album_id>
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name = 'detail'),
    # /music/add
    url(r'album/add/$', views.AlbumCreate.as_view(), name = "album-add"),
    # /music/album/2
    url(r'album/(?P<pk>[0-9]+)/edit$', views.AlbumUpdate.as_view(), name = 'album-update'),
    # /music/album/2/delete
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name = 'album-delete'),
    # register
    url(r'^register/$', views.UserFormView.as_view(), name = 'register'),

    url(r'song/add/$', views.SongCreate.as_view(), name = "song-add"),
]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

# look at URL requested and perform a functionality. Table of contents for application.

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')), # goes to music/urls.py to handle the route.
    url(r'^', include('music.urls')),

]

if settings.DEBUG: # when in developer mode, use these
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.core.urlresolvers import reverse


# Create your models here. Blueprint for database- how are we sorting data for our app?
class Album(models.Model): # all classes have to inherit from this
    artist = models.CharField(max_length=250) # going to be a column in our database!
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs = {'pk' : self.pk})

    def __str__(self): # gives string representation of the object!
        return self.album_title + ' - ' + self.artist

class Song(models.Model): # songs need to be a part of an album.
    album = models.ForeignKey(Album, on_delete= models.CASCADE) # assigns song to album with a unique ID, the foreignkey.
    # when album is deleted, also delete the songs. Each album can be a set that we can add songs to.
    file_type = models.CharField(max_length = 10)
    song_title = models.CharField(max_length= 250)
    # is_favorite = models.BooleanField(default= False)

    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password']# fields we want to appear in the form

music/views.py
from django.views import generic
from .models import Album, Song
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login # takes user and password and verifies login, gives session ID
from django.views.generic import View
from .forms import UserForm
from django.core.urlresolvers import reverse_lazy

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    # attributes we need from the user
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class SongCreate(CreateView):
    model = Song
    # attributes we need from the user
    fields = ['album', 'file_type', 'song_title']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index') #redirect to here after delete

class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'
    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit = False) # not saved to db yet
            # clean (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save() # save to db

            user = authenticate(username = username, password = password) # verify user in db

            if user is not None:
                if user.is_active:
                    login(request, user)
                     # redirect to homepage after login:
                    return redirect('music:index')

            return render(request, self.template_name, {'form': form})

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %} Add New Album {% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Album</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Add Album</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{%  endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viber{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    {#Import remote bootstrap file first #}
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


</head>
<body>
<nav class="navbar navbar-inverse bg-inverse">
    <div class = 'container-fluid'>
{# Logo#}
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">﻿

                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Viber</a>
        </div>
    <!--Items-->
    <div class="collapse navbar-collapse" id = "topNavBar">
{#        These are the items to be collapsed, identified by topNavBar#}
        <ul class="nav navbar-nav">
            <li class = "active">
                <a href = {% url 'music:index' %}>
                    <span class = "glyphicon glyphicon-cd" aria-hidden = "true"></span>&nbsp;Albums
                </a>
            </li>
            <li class = "">
                <a href = "#">
                    <span class = "glyphicon glyphicon-music" aria-hidden = "true"></span>&nbsp;Songs
                </a>
            </li>
        </ul>

        <form class = "navbar-form navbar-left" role = "search" method = "get" action = "#">
            <div class = "form-group">
                <input type = "text" class = "form-control" name = "query" value = "">
            </div>
                <button type = "submit" class = "btn btn-default">Search</button>
        </form>
        <ul class = "nav navbar-nav navbar-right">
             <li class = "">
                <a href = {% url 'music:album-add' %}>
                    <span class = "glyphicon glyphicon-plus" aria-hidden = "true"></span>&nbsp;Add Album
                </a>
            </li>

             <li class = "">
                <a href = {% url 'music:register' %}>
                    <span class = "glyphicon glyphicon-log-in" aria-hidden = "true"></span>&nbsp;Sign In
                </a>
            </li>
        </ul>
     </div>
    </div>

</nav>
{% block body %}
{#    Need this as dynamic part of the code#}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %} Album Details {% endblock %}
{% block body %}

    <img src = "{{ album.album_logo.url }}" style = "max-width: 250px; max-height: 250px">
    <h1>{{ album.album_title }}</h1>
    <h2> {{ album.artist }} </h2>


<ul>
    {% for song in album.song_set.all %}
    <li>{{ song.song_title }} - {{ song.file_type }}</li>
    {% endfor %}
</ul>

<a href = {% url 'music:song-add' %}>Add Song</a>



{%  endblock %}

music/templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
{#    input (empty text box^ #}
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block body %}

        {% for album in all_albums %}
        {#listview stores everything in object_list, which we renamed. #}
        <div class = 'col-sm-4 col-lg-2'>

          <a href = "{% url 'music:detail' album.id %}">
            <img src = "{{ album.album_logo.url }}" class = "img-responsive">
           </a>

        <a href = "{% url 'music:detail' album.id %}">{{ album.album_title }}</a>


        <!-- Delete Button -->
        <form action = "{% url 'music:album-delete' album.id %}" method = 'post' style = "display: inline;">
        {% csrf_token %}
        <input type = "hidden" name = "album_id" value = "{{album.id}}"/>
        <button type = "submit" class = "btn btn-default btn-sm">
          <span class = "glyphicon glyphicon-trash"></span>
        </button>
      </form>

      <!-- Edit button -->
      <form action = "{% url 'music:album-update' album.id %}" method = 'post' style = "display: inline;">
      {% csrf_token %}
      <input type = "hidden" name = "album_id" value = "{{album.id}}"/>
      <button type = "submit" class = "btn btn-default btn-sm">
        <span class = "glyphicon glyphicon-edit"></span>
      </button>
    </form>
    </div>
        {% endfor %}


{%  endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %} Register for Viber {% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Sign in or Create a New Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Register</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{%  endblock %}

music/templates/music/song_form.html
{% extends 'music/base.html' %}
{% block title %} Add New Song {% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Song</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Add Song</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{%  endblock %}